use_remote_connection: false
# Optional, required if use_remote_connection is true.
#  remote_connection_url: https://www.example.com
sync_interval_seconds: 120
browsers:
  chrome:
    enabled: true
    profiles: [Default]
  firefox:
    profiles: [default]
    enabled: true
# Log level options: info, debug, error
log_level: info
