[project]
name = "syncmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pyyaml>=6.0.2",
    "types-pyyaml>=6.0.12.20250402",
]
